"use client";

import { useMemo, useState } from "react";
import { mockTrades } from "@/lib/strategy-control/mock-trades";
import { mockStrategies } from "@/lib/strategy-control/mock-strategies";
import { analyzeTrades } from "@/lib/strategy-control/engine";
import { formatRuleParams } from "@/lib/strategy-control/rule-label";
import { ruleLibrary } from "@/lib/strategy-control/rule-library";
import { StrategyBuilder } from "./strategy-builder";
import type { RuleFinding, RuleStatus, StrategyProfile, Trade } from "@/lib/strategy-control/types";

const statusLabel: Record<RuleStatus, string> = { ok: "В нормі", warning: "Потребує уваги", critical: "Критично", insufficient: "Мала вибірка" };
const statusClass: Record<RuleStatus, string> = {
  ok: "border-emerald-400/30 bg-emerald-400/[0.12] text-emerald-200",
  warning: "border-amber-400/30 bg-amber-400/[0.12] text-amber-200",
  critical: "border-rose-400/35 bg-rose-400/[0.14] text-rose-200",
  insufficient: "border-slate-400/25 bg-slate-400/[0.1] text-slate-200",
};

function Metric({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return <div className="rounded-2xl border border-white/[0.07] bg-black/30 p-5"><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight text-white">{value}</p>{hint ? <p className="mt-1 text-xs text-white/35">{hint}</p> : null}</div>;
}

function Modal({ title, tone = "neutral", children, onClose }: { title: string; tone?: "neutral" | "positive" | "negative"; children: React.ReactNode; onClose: () => void }) {
  const toneClass = tone === "positive" ? "border-emerald-300/25 shadow-[0_0_80px_rgba(52,211,153,0.12)]" : tone === "negative" ? "border-rose-300/25 shadow-[0_0_80px_rgba(251,113,133,0.12)]" : "border-white/10 shadow-2xl";
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-5" onClick={onClose}><section className={`max-h-[82vh] w-full max-w-2xl overflow-y-auto rounded-3xl border bg-[#101217] p-6 ${toneClass}`} onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-white">{title}</h2><button onClick={onClose} className="rounded-full border border-white/10 px-3 py-1 text-lg leading-none text-white/50 hover:bg-white/[0.08]">×</button></div><div className="mt-6">{children}</div></section></div>;
}

function Finding({ finding, strategy, onOpen }: { finding: RuleFinding; strategy: StrategyProfile; onOpen: (finding: RuleFinding) => void }) {
  const rule = strategy.rules.find((item) => item.ruleType === finding.ruleType);
  const positive = finding.impactStatus === "positive";
  const negative = finding.impactStatus === "negative";
  return <div className={`border-b px-5 py-4 last:border-0 ${negative ? "border-rose-300/10 bg-rose-300/[0.025]" : positive ? "border-emerald-300/10 bg-emerald-300/[0.025]" : "border-white/[0.06]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-white">{finding.title} {rule ? <span className="text-white/40">{formatRuleParams(rule)}</span> : null}</p><p className="mt-1 text-xs text-white/40">{finding.category}</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full border px-2.5 py-1 text-[10px] uppercase tracking-[0.12em] ${statusClass[finding.status]}`}>{statusLabel[finding.status]}</span><span className={`rounded-full border px-2.5 py-1 text-[10px] uppercase tracking-[0.12em] ${positive ? "border-emerald-300/30 bg-emerald-300/[0.12] text-emerald-200" : negative ? "border-rose-300/30 bg-rose-300/[0.12] text-rose-200" : "border-white/10 bg-white/[0.04] text-white/45"}`}>{positive ? "Позитивний вплив" : negative ? "Негативний вплив" : "Нейтральний вплив"}</span></div></div><p className="mt-3 text-sm text-white/65">{finding.message}</p><div className="mt-3 flex flex-wrap gap-5 text-xs text-white/45"><span>Порушень: <b className="text-white/80">{finding.violations}</b></span><span>Угод: <b className="text-white/80">{finding.affectedTrades}</b></span><span>Вплив: <b className={finding.impactR < 0 ? "text-rose-300" : "text-emerald-300"}>{finding.impactR > 0 ? "+" : ""}{finding.impactR}R</b></span><span>Надійність: <b className="text-white/80">{finding.confidence}</b></span></div>{finding.compliantAvgR !== null && finding.violatedAvgR !== null ? <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg border border-emerald-300/20 bg-emerald-300/[0.08] px-3 py-2"><p className="text-[10px] uppercase tracking-[0.1em] text-emerald-300/70">за дотримання ({finding.compliantCount})</p><p className="mt-1 text-sm font-medium text-emerald-200">{finding.compliantAvgR >= 0 ? "+" : ""}{finding.compliantAvgR}R</p></div><div className="rounded-lg border border-rose-300/20 bg-rose-300/[0.08] px-3 py-2"><p className="text-[10px] uppercase tracking-[0.1em] text-rose-300/70">за порушення ({finding.affectedTrades})</p><p className="mt-1 text-sm font-medium text-rose-200">{finding.violatedAvgR >= 0 ? "+" : ""}{finding.violatedAvgR}R</p></div></div> : null}{finding.recommendation ? <p className="mt-3 rounded-xl border border-blue-300/15 bg-blue-300/[0.05] px-3 py-2 text-xs leading-5 text-white/70">{finding.recommendation}</p> : null}<button onClick={() => onOpen(finding)} className="mt-3 text-xs text-blue-300 hover:text-blue-200">Деталі правила →</button></div>;
}

export function StrategyControlPage() {
  const [strategies, setStrategies] = useState<StrategyProfile[]>(mockStrategies);
  const [strategyId, setStrategyId] = useState(mockStrategies[0].id);
  const [start, setStart] = useState("2026-03-01");
  const [end, setEnd] = useState("2026-06-30");
  const [showBuilder, setShowBuilder] = useState(false);
  const [conditionModal, setConditionModal] = useState(false);
  const [selectedFinding, setSelectedFinding] = useState<RuleFinding | null>(null);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const activeStrategy = strategies.find((s) => s.id === strategyId) ?? strategies[0];
  const filteredTrades = useMemo(() => mockTrades.filter((trade) => trade.date >= start && trade.date <= end), [start, end]);
  const analysis = useMemo(() => analyzeTrades(filteredTrades, activeStrategy, { start, end }), [filteredTrades, activeStrategy, start, end]);
  const violatedIds = new Set(analysis.findings.flatMap((finding) => finding.evidenceTradeIds));
  const compliantTrades = filteredTrades.filter((trade) => !violatedIds.has(trade.id));
  const violatedTrades = filteredTrades.filter((trade) => violatedIds.has(trade.id));
  const compliantR = compliantTrades.reduce((sum, trade) => sum + trade.resultR, 0);
  const violatedR = violatedTrades.reduce((sum, trade) => sum + trade.resultR, 0);
  const riskLabel = analysis.disciplineRisk >= 60 ? "Високий" : analysis.disciplineRisk >= 30 ? "Середній" : "Низький";

  const duplicateStrategy = () => { const copy = { ...activeStrategy, id: `${activeStrategy.id}-copy-${Date.now()}`, name: `${activeStrategy.name} (копія)`, createdAt: new Date().toISOString().slice(0, 10), rules: activeStrategy.rules.map((rule) => ({ ...rule, params: { ...rule.params } })) }; setStrategies((prev) => [...prev, copy]); setStrategyId(copy.id); };
  const handleDelete = (id: string) => { if (strategies.length <= 1) return; const remaining = strategies.filter((s) => s.id !== id); setStrategies(remaining); if (strategyId === id) setStrategyId(remaining[0].id); setConfirmDeleteId(null); };

  if (showBuilder) return <main className="min-h-screen bg-[#08090b] px-5 py-8 text-white md:px-8"><div className="mx-auto max-w-[900px]"><p className="text-[10px] uppercase tracking-[0.24em] text-blue-300/60">Trade Vault · конструктор стратегій</p><h1 className="mt-3 text-2xl font-semibold tracking-tight">Нова стратегія</h1><p className="mt-2 text-sm text-white/45">Створення нової стратегії не впливає на раніше створені.</p><div className="mt-5"><StrategyBuilder onSave={(strategy) => { setStrategies((prev) => [...prev, strategy]); setStrategyId(strategy.id); setShowBuilder(false); }} onCancel={() => setShowBuilder(false)} /></div></div></main>;

  return <main className="min-h-screen bg-[#08090b] px-5 py-8 text-white md:px-8"><div className="mx-auto max-w-[1400px]"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.24em] text-blue-300/60">Trade Vault · behavioral layer</p><h1 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">Контроль стратегії</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/45">Не дублює загальний P&amp;L. Показує, наскільки виконувались правила саме обраної стратегії.</p></div><div className="flex flex-wrap items-center gap-2 rounded-2xl border border-white/[0.07] bg-black/30 p-2"><label className="text-[10px] uppercase tracking-[0.12em] text-white/35">Від<input type="date" value={start} onChange={(e) => setStart(e.target.value)} className="ml-2 rounded-lg border border-white/10 bg-white/[0.05] px-2 py-1.5 text-xs text-white outline-none" /></label><label className="text-[10px] uppercase tracking-[0.12em] text-white/35">До<input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className="ml-2 rounded-lg border border-white/10 bg-white/[0.05] px-2 py-1.5 text-xs text-white outline-none" /></label></div></div>

  <div className="mt-6 flex flex-wrap items-center gap-3 rounded-2xl border border-white/[0.07] bg-black/25 p-4"><label className="text-[10px] uppercase tracking-[0.12em] text-white/35">Стратегія<select value={strategyId} onChange={(e) => setStrategyId(e.target.value)} className="ml-2 rounded-lg border border-white/10 bg-white/[0.05] px-3 py-1.5 text-xs text-white outline-none">{strategies.map((s) => <option key={s.id} value={s.id} className="bg-black">{s.name}</option>)}</select></label><p className="text-xs text-white/40">{activeStrategy.description}</p><button onClick={() => setConditionModal(true)} className="rounded-lg border border-blue-300/25 bg-blue-300/[0.1] px-3 py-1.5 text-xs text-blue-200">Умови стратегії</button><div className="ml-auto flex flex-wrap gap-2"><button onClick={() => setShowBuilder(true)} className="rounded-lg border border-emerald-300/25 bg-emerald-300/[0.1] px-3 py-1.5 text-xs text-emerald-200">+ Створити стратегію</button><button onClick={duplicateStrategy} className="rounded-lg border border-blue-300/20 bg-blue-300/[0.08] px-3 py-1.5 text-xs text-blue-200">Дублювати як нову</button>{confirmDeleteId === activeStrategy.id ? <button onClick={() => handleDelete(activeStrategy.id)} className="rounded-lg border border-rose-400/40 bg-rose-400/[0.16] px-3 py-1.5 text-xs text-rose-200">Підтвердити видалення?</button> : <button onClick={() => setConfirmDeleteId(activeStrategy.id)} disabled={strategies.length <= 1} className="rounded-lg border border-rose-300/20 bg-rose-300/[0.06] px-3 py-1.5 text-xs text-rose-300 disabled:opacity-30">Видалити</button>}</div></div>

  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Виконання правил" value={`${analysis.compliance}%`} hint={`${analysis.trades} угод у періоді`} /><Metric label="Дисциплінарний ризик" value={`${analysis.disciplineRisk}/100`} hint={riskLabel} /><Metric label="Winrate" value={`${analysis.winRate}%`} hint="Описова метрика періоду" /><Metric label="Результат" value={`${analysis.totalR >= 0 ? "+" : ""}${analysis.totalR}R`} hint={`avg ${analysis.averageR}R / trade`} /><Metric label="Середній ризик" value={`${analysis.averageRisk}%`} hint="На одну угоду" /></section>

  <section className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><div className="rounded-2xl border border-white/[0.07] bg-black/25"><div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-4"><div><h2 className="text-sm font-medium text-white">Правила стратегії: {activeStrategy.name}</h2><p className="mt-1 text-xs text-white/35">Факти, порушення та їхній результат</p></div><span className="text-xs text-white/35">{analysis.findings.filter((f) => f.status !== "ok").length} потребують уваги</span></div>{analysis.findings.map((finding) => <Finding key={finding.ruleType} finding={finding} strategy={activeStrategy} onOpen={setSelectedFinding} />)}</div><div className="space-y-5"><div className="rounded-2xl border border-white/[0.07] bg-black/25 p-5"><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">RR / P&amp;L summary</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Середній RR" value={analysis.averagePlannedRR === null ? "—" : `${analysis.averagePlannedRR}R`} hint="Доступні угоди" /><Metric label="Медіанний RR" value={analysis.medianPlannedRR === null ? "—" : `${analysis.medianPlannedRR}R`} hint="Плановий" /></div><div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Без порушень" value={`${compliantR >= 0 ? "+" : ""}${compliantR.toFixed(2)}R`} hint={`${compliantTrades.length} угод`} /><Metric label="З порушеннями" value={`${violatedR >= 0 ? "+" : ""}${violatedR.toFixed(2)}R`} hint={`${violatedTrades.length} угод`} /></div><p className="mt-4 text-xs leading-5 text-white/35">Порівняння описове: воно показує зв’язок у цьому періоді, але не доводить причинність.</p></div><div className="rounded-2xl border border-white/[0.07] bg-black/25 p-5"><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">Поточний фокус</p><h2 className="mt-3 text-xl font-semibold text-white">{analysis.recommendations[0] ? "Є над чим працювати" : "Система виконана чисто"}</h2><div className="mt-4 space-y-3">{(analysis.recommendations.length ? analysis.recommendations.slice(0, 4) : ["За активними правилами критичних рекомендацій немає."]).map((recommendation) => <div key={recommendation} className="rounded-xl border border-white/[0.06] bg-white/[0.025] p-3 text-sm leading-5 text-white/65">{recommendation}</div>)}</div></div></div></section></div>

  {conditionModal ? <Modal title={`Умови: ${activeStrategy.name}`} onClose={() => setConditionModal(false)}><p className="text-sm leading-6 text-white/50">{activeStrategy.description || "Умови активної стратегії"}</p><div className="mt-5 space-y-3">{activeStrategy.rules.filter((rule) => rule.enabled).map((rule) => <div key={rule.ruleType} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-3"><p className="text-sm text-white">{ruleLibrary[rule.ruleType].title} <span className="text-white/40">{formatRuleParams(rule)}</span></p><p className="mt-1 text-xs text-white/40">{ruleLibrary[rule.ruleType].description}</p></div>)}</div></Modal> : null}
  {selectedFinding ? <Modal title={selectedFinding.title} tone={selectedFinding.impactStatus === "positive" ? "positive" : selectedFinding.impactStatus === "negative" ? "negative" : "neutral"} onClose={() => setSelectedFinding(null)}><div className="space-y-4"><div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-4"><p className="text-xs uppercase tracking-[0.12em] text-white/35">Висновок</p><p className="mt-2 text-sm leading-6 text-white/70">{selectedFinding.message}</p><p className="mt-2 text-xs text-white/40">Статус: {statusLabel[selectedFinding.status]} · Надійність: {selectedFinding.confidence}</p></div><div className="grid grid-cols-2 gap-3"><Metric label="Порушень" value={`${selectedFinding.violations}`} /><Metric label="Вплив" value={`${selectedFinding.impactR >= 0 ? "+" : ""}${selectedFinding.impactR}R`} /></div>{selectedFinding.compliantAvgR !== null && selectedFinding.violatedAvgR !== null ? <div className="grid grid-cols-2 gap-3"><Metric label="Дотримано" value={`${selectedFinding.compliantAvgR >= 0 ? "+" : ""}${selectedFinding.compliantAvgR}R`} hint={`${selectedFinding.compliantCount} угод`} /><Metric label="Порушено" value={`${selectedFinding.violatedAvgR >= 0 ? "+" : ""}${selectedFinding.violatedAvgR}R`} hint={`${selectedFinding.affectedTrades} угод`} /></div> : null}{selectedFinding.recommendation ? <div className="rounded-xl border border-blue-300/15 bg-blue-300/[0.05] p-4 text-sm leading-6 text-white/65">{selectedFinding.recommendation}</div> : null}<div className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-4"><p className="text-xs uppercase tracking-[0.12em] text-white/35">Доказові угоди</p><p className="mt-2 text-sm text-white/50">Точний список угод буде підключено після інтеграції реального журналу.</p><button onClick={() => { window.location.href = `/journal?rule=${selectedFinding.ruleType}&strategy=${activeStrategy.id}&start=${start}&end=${end}`; }} className="mt-3 rounded-lg border border-blue-300/20 bg-blue-300/[0.08] px-3 py-2 text-xs text-blue-200">Відкрити фільтр у журналі</button></div><p className="text-xs leading-5 text-white/35">Обмеження: порівняння описове й не доводить причинність. Не використовуй його як автоматичний сигнал збільшення ризику.</p></div></Modal> : null}
  </main>;
}
