export type DbJournalTradeRow = {
  id: string;
  account_id: string;
  source_type: "manual" | "mt5" | "mt4" | "binance" | "bybit" | "other";
  direction: "Long" | "Short";
  status: string | null;
  market: string | null;
  raw_symbol: string | null;
  normalized_symbol: string | null;
  symbol_root: string | null;
  symbol_path: string | null;
  asset_class: string | null;
  base_asset: string | null;
  quote_asset: string | null;
  entry_price: number | null;
  exit_price: number | null;
  stop_loss: number | null;
  take_profit: number | null;
  risk_percent: number | null;
  pnl_usd: number | null;
  pnl_r: number | null;
  commission: number | null;
  swap: number | null;
  opened_at: string | null;
  closed_at: string | null;
  session: string | null;
  setup: string | null;
  htf_bias: string | null;
  entry_reason: string | null;
  exit_reason: string | null;
  emotion: string | null;
  mistake: string | null;
  screenshot_url: string | null;
  notes: string | null;
  created_at: string;
};
