import type { Trade } from "./types";

export const mockTrades: Trade[] = [
  { id: "t-001", date: "2026-03-09", pair: "GBP/USD", direction: "Long", session: "London", resultR: 1.7, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-002", date: "2026-03-11", pair: "BTC/USDT", direction: "Short", session: "Asia", resultR: -0.2, riskPct: 1, emotion: "Calm", modelConfirmed: false },
  { id: "t-003", date: "2026-03-11", pair: "ETH/USDT", direction: "Short", session: "Asia", resultR: -0.5, riskPct: 0.6, emotion: "Calm", modelConfirmed: false },
  { id: "t-004", date: "2026-03-12", pair: "XAU/USD", direction: "Long", session: "NY", resultR: -0.6, riskPct: 0.6, emotion: "Neutral", modelConfirmed: false },
  { id: "t-005", date: "2026-03-12", pair: "XAG/USD", direction: "Long", session: "NY", resultR: -1.2, riskPct: 1.3, emotion: "Angry", modelConfirmed: true },
  { id: "t-006", date: "2026-03-18", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 0, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-007", date: "2026-03-18", pair: "EUR/USD", direction: "Short", session: "NY", resultR: -0.4, riskPct: 0.5, emotion: "Calm", modelConfirmed: true },
  { id: "t-008", date: "2026-03-19", pair: "EUR/USD", direction: "Short", session: "London", resultR: -0.4, riskPct: 0.4, emotion: "Angry", modelConfirmed: false },
  { id: "t-009", date: "2026-03-23", pair: "EUR/USD", direction: "Short", session: "NY", resultR: -1.2, riskPct: 1.2, emotion: "Neutral", modelConfirmed: false },
  { id: "t-010", date: "2026-03-23", pair: "BTC/USDT", direction: "Short", session: "NY", resultR: 0.45, riskPct: 0.7, emotion: "Neutral", modelConfirmed: true },
  { id: "t-011", date: "2026-03-25", pair: "BTC/USDT", direction: "Short", session: "Asia", resultR: -0.7, riskPct: 0.7, emotion: "Neutral", modelConfirmed: true },
  { id: "t-012", date: "2026-03-25", pair: "BTC/USDT", direction: "Short", session: "NY", resultR: 3, riskPct: 0.6, emotion: "Angry", modelConfirmed: true },
  { id: "t-013", date: "2026-03-25", pair: "ETH/USDT", direction: "Short", session: "NY", resultR: 0.05, riskPct: 0.5, emotion: "Angry", modelConfirmed: false },
  { id: "t-014", date: "2026-04-07", pair: "GBP/USD", direction: "Short", session: "London", resultR: -0.5, riskPct: 0.5, emotion: "Angry", modelConfirmed: true },
  { id: "t-015", date: "2026-04-07", pair: "BTC/USDT", direction: "Short", session: "NY", resultR: -0.8, riskPct: 0.9, emotion: "Calm", modelConfirmed: true },
  { id: "t-016", date: "2026-04-07", pair: "ETH/USDT", direction: "Short", session: "NY", resultR: -0.5, riskPct: 0.5, emotion: "Calm", modelConfirmed: true },
  { id: "t-017", date: "2026-04-14", pair: "XAU/USD", direction: "Long", session: "NY", resultR: 3.8, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-018", date: "2026-04-20", pair: "EUR/USD", direction: "Short", session: "London", resultR: -0.71, riskPct: 0.7, emotion: "Neutral", modelConfirmed: true },
  { id: "t-019", date: "2026-04-20", pair: "EUR/USD", direction: "Short", session: "London", resultR: -0.3, riskPct: 0.3, emotion: "Angry", modelConfirmed: true },
  { id: "t-020", date: "2026-04-20", pair: "GBP/USD", direction: "Short", session: "NY", resultR: -0.45, riskPct: 0.5, emotion: "Angry", modelConfirmed: true },
  { id: "t-021", date: "2026-04-20", pair: "EUR/USD", direction: "Short", session: "NY", resultR: -0.71, riskPct: 0.7, emotion: "Angry", modelConfirmed: true },
  { id: "t-022", date: "2026-04-20", pair: "XAU/USD", direction: "Long", session: "London", resultR: 1.5, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-023", date: "2026-04-27", pair: "BTC/USDT", direction: "Short", session: "Asia", resultR: -0.4, riskPct: 0.4, emotion: "Calm", modelConfirmed: false },
  { id: "t-024", date: "2026-04-27", pair: "GBP/USD", direction: "Short", session: "London", resultR: 1.6, riskPct: 1.5, emotion: "Calm", modelConfirmed: true },
  { id: "t-025", date: "2026-04-27", pair: "GBP/USD", direction: "Short", session: "NY", resultR: 4, riskPct: 0.4, emotion: "Calm", modelConfirmed: true },
  { id: "t-026", date: "2026-04-27", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 4.83, riskPct: 0.6, emotion: "Calm", modelConfirmed: true },
  { id: "t-027", date: "2026-05-28", pair: "XAU/USD", direction: "Short", session: "NY", resultR: -0.6, riskPct: 0.6, emotion: "Neutral", modelConfirmed: true },
  { id: "t-028", date: "2026-05-28", pair: "GBP/USD", direction: "Short", session: "NY", resultR: -1, riskPct: 1, emotion: "Neutral", modelConfirmed: false },
  { id: "t-029", date: "2026-05-28", pair: "EUR/USD", direction: "Short", session: "NY", resultR: -1.05, riskPct: 1.05, emotion: "Neutral", modelConfirmed: false },
  { id: "t-030", date: "2026-05-28", pair: "GBP/USD", direction: "Short", session: "NY", resultR: -1.1, riskPct: 1.1, emotion: "Neutral", modelConfirmed: false },
  { id: "t-031", date: "2026-05-28", pair: "EUR/USD", direction: "Short", session: "NY", resultR: -0.66, riskPct: 0.66, emotion: "Neutral", modelConfirmed: false },
  { id: "t-032", date: "2026-06-02", pair: "XAU/USD", direction: "Long", session: "NY", resultR: -0.95, riskPct: 1, emotion: "Neutral", modelConfirmed: true },
  { id: "t-033", date: "2026-06-02", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 3.97, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-034", date: "2026-06-02", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 1.2, riskPct: 1, emotion: "Calm", modelConfirmed: true },
  { id: "t-035", date: "2026-06-02", pair: "XAU/USD", direction: "Long", session: "NY", resultR: -1, riskPct: 1, emotion: "Neutral", modelConfirmed: true },
  { id: "t-036", date: "2026-06-03", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 0.6, riskPct: 0.6, emotion: "Calm", modelConfirmed: true },
  { id: "t-037", date: "2026-06-04", pair: "EUR/USD", direction: "Short", session: "London", resultR: -1.2, riskPct: 1.2, emotion: "Neutral", modelConfirmed: true },
  { id: "t-038", date: "2026-06-04", pair: "XAU/USD", direction: "Short", session: "NY", resultR: 3.5, riskPct: 1.6, emotion: "Calm", modelConfirmed: true },
  { id: "t-039", date: "2026-06-04", pair: "EUR/USD", direction: "Short", session: "NY", resultR: 2.4, riskPct: 0.4, emotion: "Calm", modelConfirmed: true },
];
